version: '3'
services:
  static3-backend:
    container_name: 'scrape-static3-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-static3-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD:
      PGSQL_DATABASE: 'scrape_maoyan'