version: '3'
services:
  captcha2-backend:
    container_name: 'scrape-captcha2-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-captcha2-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      CAPTCHA_TYPE: 'SLIDE'
  captcha2-frontend:
    container_name: 'scrape-captcha2-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-captcha2-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'captcha2-backend'
    ports:
      - '8083:80'