version: '3'
services:
  dynamic2-backend:
    container_name: 'scrape-dynamic2-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-dynamic2-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD:
      PGSQL_DATABASE: 'scrape_maoyan'
  dynamic2-frontend:
    container_name: 'scrape-dynamic2-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-dynamic2-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'dynamic2-backend'
    ports:
      - '8083:80'